---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "0-main"
  namespace: openshift-gitops
  finalizers:
   - resources-finalizer.argocd.argoproj.io
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  labels:
    app.kubernetes.io/part-of: "{{ .Values.resourceNamePrefix }}"
spec:
  project: default

  source:
    repoURL: "{{ .Values.git.repository.repoURL }}"
    targetRevision: "{{ .Values.git.repository.targetRevision }}"
    path: "{{ .Values.git.repository.mainAppPath }}"
    helm:
      valueFiles:
      - values.yaml

  # Destination cluster and namespace to deploy the application
  destination:
    # name: change-me
    name: in-cluster
    namespace: openshift-gitops
    
  # NO NEED TO CHANGE BELOW PARAMS

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 900s


  # Apply metadata to namespaces
  # managedNamespaceMetadata:
  #   labels:
  #     argocd.argoproj.io/managed-by: openshift-gitops
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '0'

  # ignoreDifferences:
  # - group: oadp.openshift.io
  #   kind: DataProtectionApplication
  #   jqPathExpressions:
  #     - '.spec.backupLocations'
  #     - '.spec.snapshotLocations'
  #     - '.spec.configuration.featureFlags'
  #     - '.spec.configuration.nodeAgent'

  revisionHistoryLimit: 10