clusterName: aroclassic102

enabled: true
defaultVolumesToFsBackup: false # Whether or not use snapshots ofr FileSystem Backup for Volumes

projects: # List projects/namespaces to backup
  - namespace: warehouse
    paused: false
    cronSchedule: "0 */4 * * *" # Every day at midnight - update accordingly for other TZ
    backupRetentionPeriod: 720h # 30 days
  - namespace: point-of-sale
    paused: false
    cronSchedule: "0 */4 * * *" # Every day at midnight - update accordingly for other TZ
    backupRetentionPeriod: 720h # 30 days
  - namespace: shipping
    paused: false
    cronSchedule: "0 */4 * * *" # Every day at midnight - update accordingly for other TZ
    backupRetentionPeriod: 720h # 30 days
