
# Add more groups and roles for RBAC configuration
rbac:
  policies: []
  # Reference: https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
    # - group: MY_GROUP
    #   role: my_role

git:
  repository:
    name: aro-gitops
    repoURL: 'https://github.com/luqmanbarry/aro-classic-terraform.git' # Don't leave out the .git for the url
    targetRevision: main
    username: git
    password: 'changeme'
    insecureTLS: true