clusterName: 'aroclassic102'

git:
  targetRevision: main

# Helm does not support merge for variables of type list. 
# The complete list have be provided if variable specified.
modules:
  - name: openshift-gitops
    config_path: gitops/argocd-init/openshift-gitops
    sync_wave: 0
  - name: openshift-compliance
    config_path: gitops/modules/compliance-operator
    sync_wave: 2
  - name: container-security
    config_path: gitops/modules/container-security
    sync_wave: 3