apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    managed-by: argocd.argoproj.io
    # argocd.argoproj.io/sync-wave: "1"
    "helm.sh/hook": ""
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: cluster
{{ if not .Values.disableSelfProvisioner }}
spec: {}
{{ else }}
spec:
  projectRequestMessage: "To request a project/namespace, contact your system administrator at {{ .Values.clusterAdminEmail }}."
{{ end }}
