clusterName: aroclassic102

storageClassMapping:
  oldStorageClassName: managed-premium
  newStorageClassName: managed-csi

enable: false
backups: # List backups to restore from
  - warehouse-20241101160045
  - shipping-20241101160045
  - point-of-sale-20241101160045