clusterName: aroclassic102

storageClassMapping:
  oldStorageClassName: managed-premium
  newStorageClassName: managed-csi

enable: true
backups: # List backups to restore from
  - warehouse-20241114160002
  - shipping-20241114160002
  - point-of-sale-20241114160002