# Source: https://github.com/nginxinc/nginx-ingress-helm-operator/blob/main/helm-charts/nginx-ingress/values.yaml
keyVaultName: stig0012-dev-vault
clusterName: aroclassic102
defaultTLS:
  enable: false
  certificateKVSecretName: nginx-ingress-tls # Merge tls.crt, tls.key data into a single file and store it in KeyVault

controller:
  - name: nginx
    image: docker.io/nginx/nginx-ingress
    tag: ''
    namespace: nginx-ingress
    replicaCount: 3
    ingressClassName: nginx
    # loadBalancerIP: Empty string means it is dynamic. For static IP Address goto https://cloud.redhat.com/experts/aro/static-ip-load-balancer/
    loadBalancerIP: '' 
    setAsDefaultIngress: false

