# Source: https://github.com/nginxinc/nginx-ingress-helm-operator/blob/main/helm-charts/nginx-ingress/values.yaml
keyVaultName: stig0014-dev-vault
clusterName: aroclassic103
defaultTLS:
  enable: false
  certificateKVSecretName: nginx-ingress-tls # Merge tls.crt, tls.key data into a single file and store it in KeyVault

controller:
  - ingressClassName: demo-nginx-ingress
    image: docker.io/nginx/nginx-ingress
    tag: ''
    namespace: demo-nginx-ingress
    replicaCount: 2
    # loadBalancerIP: Empty string means it is dynamic. For static IP Address goto https://cloud.redhat.com/experts/aro/static-ip-load-balancer/
    loadBalancerIP: ''
    setAsDefaultIngress: false

