# Source: https://github.com/nginxinc/nginx-ingress-helm-operator/blob/main/helm-charts/nginx-ingress/values.yaml
keyVaultName: stig0012-dev-vault
clusterName: aroclassic102
defaultTLS:
  enable: false
  certificateKVSecretName: nginx-ingress-tls # Merge tls.crt, tls.key data into a single file and store it in KeyVault


controllers:
  - name: nginx
    image: docker.io/nginx/nginx-ingress
    namespace: nginx-ingress
    ingressClassName: nginx
    loadBalancerIP: 10.91.2.200 # Pick one from the worker subnet IP Pool
    setAsDefaultIngress: false

