{{ range $moduleItem := .Values.modules }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $moduleItem.sync_wave }}-{{ $moduleItem.name }}"
  namespace: openshift-gitops
  finalizers:
   - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: "{{ $.Values.resourceNamePrefix }}"
spec:
  project: default

  source:
    repoURL: "{{ $.Values.git.repoURL }}"
    targetRevision: "{{ $.Values.git.targetRevision }}"
    path: "{{ $moduleItem.config_path }}"
    helm:
      valueFiles:
      - values.yaml
      - "values.{{ $.Values.clusterName }}.yaml"

  # Destination cluster and namespace to deploy the application
  destination:
    # name: change-me
    name: in-cluster
    namespace: openshift-gitops
    
  # NO NEED TO CHANGE BELOW PARAMS

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - sync-wave="{{ $moduleItem.sync_wave }}"
    - SkipDryRunOnMissingResource=true
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 1
        maxDuration: 900s


  # Apply metadata to namespaces
  # managedNamespaceMetadata:
  #   labels:
  #     argocd.argoproj.io/managed-by: openshift-gitops
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '0'

  ignoreDifferences:
  - group: operators.coreos.com/v1alpha1
    kind: Subscription
    jqPathExpressions:
      - '.spec.status'

  revisionHistoryLimit: 5
{{ end }}