
# Complete var list: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml
keyVaultName: "stig0010-dev-vault"
splunkKVSecretName: "splunk-platform-heck-token"
splunk-otel-collector: # subchart name to override its values.
  clusterName: "rh-sandbox3" # REQUIRED
  cloudProvider: "azure" # {aws|azure|gke}
  distribution: "openshift" # {eks, aks, eks/fargate,..}

  splunkPlatform:
    endpoint: "http://localhost:8088/services/collector" # REQUIRED
    secret:
      create: false
      name: your-secret
    token: "MY_ACCESS_TOKEN " # REQUIRED

    # Name of the Splunk event type index targeted. Required when ingesting logs to Splunk Platform.
    index: "rh-sandbox3" # REQUIRED