
business_unit: sales
aws_region: us-east-1
storageClassName: managed-csi
micro_services:
  - name: warehouse
    namespace: warehouse
    pvc_name: warehouse
    pvc_size: 200Gi
    image: image-registry.openshift-image-registry.svc:5000/openshift/nginx

  - name: point-of-sale
    namespace: point-of-sale
    pvc_name: point-of-sale
    pvc_size: 200Gi
    image: image-registry.openshift-image-registry.svc:5000/openshift/httpd

  - name: shipping
    namespace: shipping
    pvc_name: shipping
    pvc_size: 200Gi
    image: image-registry.openshift-image-registry.svc:5000/openshift/nginx
