rbac:
  assignments:
    - ocpRole: "cluster-admin"
      groupName: "lbarry-aro-admins"
    - ocpRole: "admin"
      groupName: "lbarry-aro-admins"
    - ocpRole: "edit"
      groupName: "lbarry-aro-admins"