
# Complete var list: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/values.yaml
keyVaultName: "stig0015-dev-vault"
hecKeyVaultSecretName: "splunk-platform-hec-details"

# splunk-otel-collector: # subchart name to override its values.
clusterName: "aroclassic102" # REQUIRED
cloudProvider: "azure" # {aws|azure|gke}
distribution: "openshift" # {eks, aks, eks/fargate,..}

splunkPlatform:
  endpoint: "http://localhost:8088/services/collector" # REQUIRED
  insecureSkipVerify: false
  index: "openshift" # REQUIRED
secret:
  create: false
  name: "splunk-platform-hec-details"

agent:
  enabled: true
  service:
    enabled: true
  extraEnvs: []
  extraVolumes: []
  extraVolumeMounts: []
  