clusterName: changeme
keyVaultName: changeme
namespace: openshift-adp
subscriptionChannel: stable-1.4


storage:
  provider: azure
  resourceGroup: stig0011-dev-tfstate
  storageAccount: stig0011devtfstate
  storageContainer: oadp
  subscriptionId: 47fb2f13-480c-4657-a103-f3779bc3f63f
  servicePrincipalClientID: f45b9c54-7933-4d79-87e3-1809cd19477d
  servicePrincipalKVStorageAccountAccessKey: oadp-storage-account-access-key
  azureCloudName: AzurePublicCloud #AzureUSGovernmentCloud, AzureChinaCloud