apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: cluster
spec:
  additionalTrustedCA:
    name: ''
  allowedRegistriesForImport: # Ref: https://access.redhat.com/solutions/6547281
    {{ toYaml .Values.allowedRegistriesForImport | nindent 4 }}
  registrySources: 
    allowedRegistries:
      # Default registries are required by OpenShift - DO NOT CHANGE
      - quay.io
      - registry.redhat.io
      - registry.connect.redhat.com
      - image-registry.openshift-image-registry.svc:5000
      # User provider registries - Provide list in values.<env>.yaml files
      {{ toYaml .Values.allowList | nindent 6 }}
      # Cloud Provider Specific Registries
      - arosvc.azurecr.io
      - arosvc.eastus.data.azurecr.io
