clusterName: 'aroclassic102'

git:
  targetRevision: main

# Helm does not support merge for variables of type list. 
# The complete list have be provided if variable specified.
modules: # List of modules to be deployed
  - name: openshift-gitops
    config_path: gitops/bootstrap/openshift-gitops
    sync_wave: 1
  - name: argocd-config
    config_path: gitops/bootstrap/argocd-config
    sync_wave: 100
  - name: external-secrets-operator
    config_path: gitops/modules/external-secrets-operator
    sync_wave: 101
  - name: secrets-store-csi-driver
    config_path: gitops/modules/secrets-store-csi-driver
    sync_wave: 101
  # - name: openshift-compliance
  #   config_path: gitops/modules/compliance-operator
  #   sync_wave: 102
  - name: container-security
    config_path: gitops/modules/container-security
    sync_wave: 103
  - name: internal-image-registry
    config_path: gitops/modules/internal-image-registry
    sync_wave: 104
  - name: self-provisioner
    config_path: gitops/modules/self-provisioner
    sync_wave: 105
  - name: user-workload-monitoring
    config_path: gitops/modules/user-workload-monitoring
    sync_wave: 106
  - name: image-registries-allow-deny
    config_path: gitops/modules/image-registries-allow-deny
    sync_wave: 107
  # - name: global-cluster-pull-secret
  #   config_path: gitops/modules/global-cluster-pull-secret
  #   sync_wave: 108
  # - name: image-registries-proxy
  #   config_path: gitops/modules/image-registries-proxy
  #   sync_wave: 109
  # - name: cluster-log-forwarder
  #   config_path: gitops/modules/cluster-log-forwarder
  #   sync_wave: 110
  - name: splunk-log-forwarder
    config_path: gitops/modules/splunk-log-forwarder
    sync_wave: 110
  - name: identity-providers
    config_path: gitops/modules/identity-providers
    sync_wave: 111
  # - name: groups-rbac
  #   config_path: gitops/modules/groups-rbac
  #   sync_wave: 112