resourceNamePrefix: 'aro-day2-gitops'
clusterName: 'changeme' # REQUIRED
git:
  repoURL: 'https://github.com/luqmanbarry/aro-classic-terraform.git' # REQUIRED
  targetRevision: main # REQUIRED

modules:
  - name: openshift-gitops
    config_path: gitops/bootstrap/openshift-gitops
    helm_hook: "pre-install,pre-upgrade" # Must deploy first
    helm_hook_weight: 100
  - name: argocd-config
    config_path: gitops/bootstrap/argocd-config
    helm_hook: "pre-install,pre-upgrade" # Must deploy first
    helm_hook_weight: 101
  - name: external-secrets-operator
    config_path: gitops/modules/external-secrets-operator
    helm_hook: "pre-install,pre-upgrade" # Must deploy first
    helm_hook_weight: 102
  - name: nginx-ingress
    config_path: gitops/modules/nginx-ingress
    helm_hook: ""
    helm_hook_weight: 114
      