clusterName: 'aroclassic102'

git:
  targetRevision: main

# Helm does not support merge for variables of type list. 
# The complete list have be provided if variable specified.
modules: # List of modules to be deployed
  - name: openshift-gitops
    config_path: gitops/bootstrap/openshift-gitops
    helm_hook: "pre-install,pre-upgrade" # Must deploy first
    helm_hook_weight: 1
  - name: argocd-config
    config_path: gitops/bootstrap/argocd-config
    helm_hook: "pre-install,pre-upgrade" # Must deploy first
    helm_hook_weight: 2
  - name: external-secrets-operator
    config_path: gitops/modules/external-secrets-operator
    helm_hook: "pre-install,pre-upgrade" # Default value
    helm_hook_weight: 3
  # - name: secrets-store-csi-driver
  #   config_path: gitops/modules/secrets-store-csi-driver
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 100
  # - name: openshift-compliance
  #   config_path: gitops/modules/compliance-operator
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 101
  - name: container-security
    config_path: gitops/modules/container-security
    helm_hook: "" # Default value
    helm_hook_weight: 102
  - name: internal-image-registry
    config_path: gitops/modules/internal-image-registry
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 103
  - name: self-provisioner
    config_path: gitops/modules/self-provisioner
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 104
  - name: user-workload-monitoring
    config_path: gitops/modules/user-workload-monitoring
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 105
  - name: image-registries-allow-deny
    config_path: gitops/modules/image-registries-allow-deny
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 106
  - name: global-cluster-pull-secret
    config_path: gitops/modules/global-cluster-pull-secret
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 107
  # - name: image-registries-proxy
  #   config_path: gitops/modules/image-registries-proxy
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 108
  # - name: cluster-log-forwarder
  #   config_path: gitops/modules/cluster-log-forwarder
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 109
  # - name: gitlab-runners
  #   config_path: gitops/modules/gitlab-runners
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 110
  # - name: splunk-otel-log-forwarder
  #   config_path: gitops/modules/splunk-otel-log-forwarder
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 110
  - name: identity-providers
    config_path: gitops/modules/identity-providers
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 111
  # - name: group-sync-operator
  #   config_path: gitops/modules/group-sync-operator
  #   sync_wave: 111
  - name: groups-rbac
    config_path: gitops/modules/groups-rbac
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 112
  - name: oadp-operator
    config_path: gitops/modules/oadp-operator
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 113
  - name: sample-apps
    config_path: gitops/modules/sample-apps
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 113
  - name: nginx-ingress
    config_path: gitops/modules/nginx-ingress
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 114
  # - name: service-mesh
  #   config_path: gitops/modules/service-mesh
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 114 
  # - name: oadp-backup
  #   config_path: gitops/modules/oadp-backup
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 115
  # - name: oadp-restore
  #   config_path: gitops/modules/oadp-restore
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 900
  # - name: openshift-cluster-upgrade
  #   config_path: gitops/modules/openshift-cluster-upgrade
  #   helm_hook: "post-install,post-upgrade" # Default value
  #   helm_hook_weight: 999
  