clusterName: 'aroclassic102'

git:
  targetRevision: main

# Helm does not support merge for variables of type list. 
# The complete list have be provided if variable specified.
modules: # List of modules to be deployed
  # - name: openshift-gitops
  #   config_path: gitops/argocd-init/openshift-gitops
  #   sync_wave: 1
  #   hasClusterValues: false
  - name: argocd-config
    config_path: gitops/argocd-init/argocd-config
    sync_wave: 2
  - name: openshift-compliance
    config_path: gitops/modules/compliance-operator
    sync_wave: 20
  - name: container-security
    config_path: gitops/modules/container-security
    sync_wave: 30
  - name: internal-image-registry
    config_path: gitops/modules/internal-image-registry
    sync_wave: 40
  - name: self-provisioner
    config_path: gitops/modules/self-provisioner
    sync_wave: 50
  - name: user-workload-monitoring
    config_path: gitops/modules/user-workload-monitoring
    sync_wave: 60
  - name: image-registries-allow-deny
    config_path: gitops/modules/image-registries-allow-deny
    sync_wave: 70