clusterName: 'aroclassic102'

git:
  targetRevision: main

# Helm does not support merge for variables of type list. 
# The complete list have be provided if variable specified.
modules: # List of modules to be deployed
  # - name: openshift-gitops
  #   config_path: gitops/bootstrap/openshift-gitops
  #   sync_wave: 1
  #   hasClusterValues: false
  - name: argocd-config
    config_path: gitops/bootstrap/argocd-config
    sync_wave: 2
  - name: external-secrets-operator
    config_path: gitops/modules/external-secrets-operator
    sync_wave: 9
  - name: openshift-compliance
    config_path: gitops/modules/compliance-operator
    sync_wave: 10
  - name: container-security
    config_path: gitops/modules/container-security
    sync_wave: 11
  - name: internal-image-registry
    config_path: gitops/modules/internal-image-registry
    sync_wave: 12
  - name: self-provisioner
    config_path: gitops/modules/self-provisioner
    sync_wave: 13
  - name: user-workload-monitoring
    config_path: gitops/modules/user-workload-monitoring
    sync_wave: 14
  - name: image-registries-allow-deny
    config_path: gitops/modules/image-registries-allow-deny
    sync_wave: 15
  - name: global-cluster-pull-secret
    config_path: gitops/modules/global-cluster-pull-secret
    sync_wave: 16