resourceNamePrefix: 'aro-day2-gitops'
clusterName: 'changeme' # REQUIRED
git:
  repoURL: 'https://github.com/luqmanbarry/aro-classic-terraform.git' # REQUIRED
  targetRevision: main # REQUIRED

modules:
  - name: openshift-gitops
    config_path: gitops/modules/container-security
    helm_hook: "post-install,post-upgrade" # Default value
    helm_hook_weight: 1
      