clusterName: aroclassic102
keyVaultName: stig0011-dev-vault

gitlab:
  runners:
    - name: openshift-cicd
      defaultImage: registry.redhat.io/openshift4/ose-tools-rhel8
      runnerImage: registry.redhat.io/openshift4/ose-tools-rhel8
      runUntagged: false
      tags: "openshift-cicd,kubernetes-cicd,"
