clusterName: changeme
namespace: gitlab-runners
keyVaultName: changeme

tlsCerts:
  enable: false # Set this flag to true to set gitlab root ca
  caKVSecretName: gitlab-instance-root-ca

runnerBaseImage: registry.redhat.io/openshift4/ose-tools-rhel9:latest

persistentVolumeClaim: # This is used to add writable filesystem to the runner pod
  storageClass: managed-csi
  size: 50Gi
  mountPath: "/mnt/cicd"

gitlabRunnerRegistrationTokenKVSecret: "gitlab-runner-registration-token"
gitlabUrl: https://gitlab.consulting.redhat.com
gitlab:
  runners:
    - name: openshift-cicd-tools
      runUntagged: false
      tags: "openshift,openshift-cicd-tools,kubernetes,kubernetes-cicd-tools"
