clusterName: changeme
namespace: gitlab-runners
keyVaultName: changeme
caKVSecretName: gitlab-instance-root-ca
gitlabRunnerRegistrationTokenKVSecret: "gitlab-runner-registration-token"
gitlabUrl: https://gitlab.example.com
gitlab:
  runners:
    - name: openshift-cicd
      defaultImage: registry.redhat.com/openshift/test:latest
      runnerImage: registry.redhat.com/openshift/test:latest
      runUntagged: false
      tags: "openshift-cicd,kubernetes-cicd,"
