clusterName: aroclassic102
keyVaultName: stig0012-dev-vault

runners:
  - name: openshift-cicd-tools
    image: image-registry.openshift-image-registry.svc:5000/gitlab-runners/openshift-cicd-tools
    concurrent: 10
    tags: "openshift,openshift-cicd-tools,kubernetes,kubernetes-cicd-tools"
  - name: python-cicd-tools
    image: image-registry.openshift-image-registry.svc:5000/gitlab-runners/python-cicd-tools
    concurrent: 10
    tags: "openshift,python-cicd-tools,kubernetes,python3,python"
  - name: java-cicd-tools
    image: image-registry.openshift-image-registry.svc:5000/gitlab-runners/java-cicd-tools
    concurrent: 10
    tags: "openshift,java-cicd-tools,kubernetes,java21,java17,java8"
  - name: nodejs-cicd-tools
    image: image-registry.openshift-image-registry.svc:5000/gitlab-runners/nodejs-cicd-tools
    concurrent: 10
    tags: "openshift,nodejs-cicd-tools,kubernetes,nodejs,npm"