clusterName: changeme
namespace: gitlab-runners
keyVaultName: changeme

helmChart:
  name: "gitlab-runner"
  repoURL: "https://charts.gitlab.io"
  targetRevision: "0.70.3"

tlsCerts:
  enable: false # Set this flag to true to set gitlab root ca
  caKVSecretName: gitlab-instance-root-ca

runnerBuildImage: registry.redhat.io/openshift4/ose-tools-rhel9:latest

persistentVolumeClaim: # This is used to add writable filesystem to the runner pod
  storageClass: managed-csi # 
  size: 50Gi
  mountPath: "/mnt/cicd"

gitlabRunnerTokenKVSecret: "gitlab-runner-registration-token"
gitlabUrl: https://gitlab.consulting.redhat.com
runners:
  - name: openshift-cicd-tools
    concurrent: 10
    runnerTokenKVSecret: changeme
    tags: "openshift,openshift-cicd-tools,kubernetes,kubernetes-cicd-tools"
