clusterName: aroclassic102
keyVaultName: stig0014-dev-vault

gitlab:
  runners:
    - name: openshift-cicd-tools
      runUntagged: false
      tags: "openshift,openshift-cicd-tools,kubernetes,kubernetes-cicd-tools"
