keyVaultName: stig0014-dev-vault
idp:
  openid:
    enable: true
    providers:
      - type: AAD
        enable: true
        name: AAD
        # Set CallBack URL on SP - Pattern: https://oauth-openshift.apps.aroclassic102-stig0014.eastus.aroapp.io/oauth2callback/AAD
        clientID: 1641416b-51c5-4aee-9a62-cdcaf386680d
        clientSecretKeyVaultSecretName: openshift-aroclassic102-aad-sp-client-secret
        issuerURL: https://login.microsoftonline.com/64dc69e4-d083-49fc-9569-ebece1dd1408/v2.0
  
    
  