keyVaultName: changeme
idp:
  openid:
    providers:
      - type: AAD
        enable: true
        name: ActiveDirectory
        # Instructions: https://cloud.redhat.com/experts/idp/group-claims/aro/
        clientID: changeme
        clientSecretKeyVaultSecretName: openshift-aroclassic102-aad-sp-client-secret
        issuerURL: https://login.microsoftonline.com/TENANT_ID/v2.0
      - type: KEYCLOAK
        enable: true
        name: KeyCloak
        clientID: changeme
        clientSecretKeyVaultSecretName: openshift-aroclassic102-aad-sp-client-secret
        issuerURL: https://keycloak-url/auth/realms/realm-name
    oauthCertsConfigMapName: oauth-config-certs
    enable: false
  