keyVaultName: changeme
idp:
  openid:
    name: KERBEROS
    clientID: changeme
    clientSecretKeyVaultSecretName: kerberos-client-secret
    issuerURL: https://www.idp-issuer.com
  oauthCertsConfigMapName: oauth-config-certs
  