keyVaultName: stig0012-dev-vault
idp:
  openid:
    providers:
      - type: AAD
        enable: true
        name: AAD
        clientID: changeme
        clientSecretKeyVaultSecretName: openshift-aroclassic102-aad-sp-client-secret
        issuerURL: https://login.microsoftonline.com/TENANT_ID/v2.0
  
    
  