apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  defaultRoute: {{ .Values.defaultRoute }}
  disableRedirect: {{ .Values.disableRedirect }}
  logLevel: Normal
  # managementState: Managed
  operatorLogLevel: Normal
  replicas: 3
  # storage:
  #   azure:
  #     accountName: {{ .Values.storage.azure.accountName }}
  #     cloudName: {{ .Values.storage.azure.cloudName }}
  #     container: image-registry
  #   managementState: Unmanaged