apiVersion: samples.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  architectures:
  - x86_64
  # managementState: Managed
  samplesRegistry: "registry.redhat.io" # Ref: https://access.redhat.com/solutions/6547281
  additionalTrustedCA:
    name: registry-ca
  allowedRegistriesForImport:
  - domainName: quay.io
    insecure: false
  - domainName: registry.redhat.io
    insecure: false
  - domainName: registry.connect.redhat.com
    insecure: false
  registrySources:
    allowedRegistries:
    - quay.io
    - registry.redhat.io