clusterName: "changeme"
keyVaultName: "changeme"
cluster_sp_k8s_secret_name: "cluster-sp-secret"
tf_resources_namespace: "ocp-tf-resources"
provider:
  azurekv: # Key Vault ServicePrincipal credentials
    clientID: changeme
    tenantID: changeme
    vaultURL: "https://my-keyvault-name.vault.azure.net"
    