namespace: openshift-compliance
clusterName: "changeme"
resourceCommonName: "stig-compliance"

scanProfiles:
  - ocp4-stig
  - rhcos4-stig
autoApplyRemediations: true
enableDebug: true
scanSchedule: 0 1 * * * # https://crontab.guru/
