namespace: openshift-compliance
clusterName: "changeme"
resourceCommonName: "stig-compliance"

scanProfiles:
  - ocp4-stig
  - rhcos4-stig
  - ocp4-stig-node
autoApplyRemediations: true
enableDebug: true
scanSchedule: 0 */4 * * * # https://crontab.guru/
