clusterName: "changeme"
registriesCertsConfigMap: registries-config-certs
# REGISTRIES ARE BLOCKED BY DEFAULT - ADD REGISTRY/IMAGE TO UNBLOCK
allowList:
  - mcr.microsoft.com
  - ghcr.io
  - gcr.io
  - public.ecr.aws
  - registry1.dso.mil