namespace: group-sync-operator
keyVaultName: stig0012-dev-vault
idp:
  aad:
    enable: true
    name: aad-group-sync
    clientID: changeme
    clientSecretKeyVaultSecretName: changeme
    tenantID: changeme
    syncCronSchedule: "*/5 * * * *"
    # List of groups to sync
    groups:
      - aro-admin
      - aro-project-owner
      - aro-viewer