resourceNamePrefix: 'aro-day2-gitops'
clusterName: 'changeme' # REQUIRED
git:
  repoURL: 'https://github.com/luqmanbarry/aro-classic-terraform.git' # REQUIRED
  targetRevision: main # REQUIRED

modules:
  - name: openshift-gitops
    config_path: gitops/argocd-init/openshift-gitops
    hasClusterValues: false
    sync_wave: 0

      